- hosts: web
  remote_user: root
  become: true
  tasks:
  - name: Install apache httpd  (state=present is optional)
    ansible.builtin.apt: 
     name: apache2
     state: present

  - name: Restart Apache
    apt: 
      name: apache2
      state: fixed

  - name: Remove Apache
    apt: 
      name: apache2
      state: absent