---
- hosts: aws-ec2
  remote_user: root
  become: yes
  gather_facts: false

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: Restart Apache
      service:
        name: httpd
        state: restat
        
    - name: Remove Apac he
      yum:
        name: httpd
        state: absent