all:
  hosts:
    web.mydomain.local.yaml:
  childern:
    customer1:
      childern:
        db:
          hosts:
            db1.mydomain.local:
            db2.mydomain.local:
        web:
          hosts:
            web.mydomain.local:
