---
- hosts: test-servers
  become: true
  vars:
    #variable needed during node installation
    # ansible_become_pass: edureka
    var_node: /tmp
  
  roles:
    - prerequisites
    - mongodb
    - nodejs